name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Choose the Python version you want to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build executable
      run: |
        pyinstaller --onefile server.py
- name: Upload artifacts
  uses: actions/upload-artifact@v2
  with:
    name: my-artifact # 你可以为此处更改名称
    path: engine_proxy/.github/workflows/
